# my nacos server service的配置文件
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-nacos-server
  name: my-nacos-server-svc
  namespace: api-gateway
spec:
  selector:
    app: my-nacos-server
  ports:
    - port: 8848
      targetPort: 8848
      name: nacos-server-port
  type: NodePort