# my gateway server deployment的配置文件
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-gateway-server
  name: my-gateway-server-deploy
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: my-gateway-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-gateway-server
    spec:
      containers:
        - image: my-gateway-server:1.0
          imagePullPolicy: IfNotPresent
          name: my-gateway-server
          ports:
            # 网关入口
            - containerPort: 8888
            # Prometheus数据拉取端口
            - containerPort: 17777
          # 通过环境变量的方式注入参数值
          # 此处环境变量的值是my-nacos-server-service的clusterIP:port
          env:
            - name: GATEWAY_registryAddress
              value: 10.97.4.70:8848
            - name: GATEWAY_configAddress
              value: 10.97.4.70:8848
      restartPolicy: Always
