# my gateway server service的配置文件
---
apiVersion: v1
kind: Service
metadata:
  labels: 
    app: my-gateway-server
  name: my-gateway-server-svc
spec:
  selector: 
    app: my-gateway-server
  ports:
  - port: 8888
    targetPort: 8888
  type: NodePort